[package]
name = "nurby"
version = "0.1.0"
edition = "2024"

[dependencies]
malachite = "0.5.0"

[dev-dependencies]
proptest = "1.6.0"

[package.metadata.docs.rs]
features = ["default"]
rustdoc-args = [
    "--cfg",
    "docsrs",
    "--html-in-header",
    "mathjax-doc-header.html",
]
